More updates

diff --git a/update-autoconf b/update-autoconf
--- a/update-autoconf
+++ b/update-autoconf
@@ -56,7 +56,7 @@ find . -name autom4te.cache -print0 | xargs -0 rm -fr || die
 
 git add . -f || die
 git stash || die
-git checkout "${BASE}" || git checkout -b "${BASE}" autoconf/master || die
+git checkout "${BASE}" || git checkout --orphan "${BASE}" || die
 git rm . -f -r
 git stash pop || die
 
@@ -71,16 +71,21 @@ fi
 
 git push -f origin "${BASE}":refs/heads/__AUTOCONF_HEAD || die
 
+COMMIT_LOG="build-system: Merge of changes for $REV
+
+Based-on: `git rev-parse $REV`"
+
 if git checkout "${FULL}"
 then
-	git merge --allow-unrelated-histories -m "build-system: Merge of changes for $REV
-
-Based-on: `git rev-parse $REV`" "${REF}" "${BASE}" || die
+	git merge --allow-unrelated-histories -m "${COMMIT_LOG}" ${REF} ${BASE} || {
+		git status --porcelain | grep '^UU' || die "Can't resolve merge"
+		git status --porcelain | grep '^UU' | awk '{print $2}' | xargs -n 1 git checkout "${REF}"
+		git status --porcelain | grep '^UU' | awk '{print $2}' | xargs -n 1 git checkout "${BASE}"
+		git commit -m "${COMMIT_LOG}" || die
+	}
 else
 	git checkout -B "${FULL}" "${REF}"
-	git merge --allow-unrelated-histories -m "build-system: Merge of changes for $REV
-
-Based-on: `git rev-parse $REV`" "${BASE}" || die
+	git merge --allow-unrelated-histories -m "${COMMIT_LOG}" || die
 fi
 
 git push -f origin "${FULL}":refs/heads/__FULL_HEAD || die
